Test failure

diff --git a/.github/workflows/solidity.yml b/.github/workflows/solidity.yml
--- a/.github/workflows/solidity.yml
+++ b/.github/workflows/solidity.yml
@@ -19,7 +19,7 @@ concurrency:
 
 jobs:
   solidity-compat:
-    runs-on: buildjet-16vcpu-ubuntu-2204
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
@@ -28,52 +28,59 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: taiki-e/install-action@nextest
-      - uses: Swatinem/rust-cache@v2
-      - run: cargo nextest run -E 'test(test_solidity_compatibility_ipa)' --release --run-ignored all
-        id: solidity-test
-        continue-on-error: true
-      # Gets the commit hash so we can retrieve detailed PR info
-      - name: Get commit hash
-        id: commit
-        if: steps.solidity-test.outcome != 'success'
+      #- uses: dtolnay/rust-toolchain@stable
+      #- uses: taiki-e/install-action@nextest
+      #- uses: Swatinem/rust-cache@v2
+      #- run: cargo nextest run -E 'test(test_solidity_compatibility_ipa)' --release --run-ignored all
+      #  id: solidity-test
+      #  continue-on-error: true
+      ## Prepares env vars for use in a PR comment or issue in `solidity-verifier`
+      - name: Set env vars
+        #if: steps.solidity-test.outcome != 'success'
         run: |
-          if [[ -s ${{ github.event.pull_request }} ]]; then
-            SHA=${{ github.event.pull_request.head_sha }}
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            SHA=${{ github.event.pull_request.head.sha }}
+            PR_NUMBER=${{ github.event.pull_request.number }}
           else
             SHA=${{ github.event.merge_group.head_sha }}
-          echo "sha=$SHA" | tee -a $GITHUB_OUTPUT
-      # Gets the PR info regardless of whether the workflow is triggered by `pull_request` or `merge_group`
-      - uses: 8BitJonny/gh-get-current-pr@3.0.0
-        if: steps.solidity-test.outcome != 'success'
-        id: pr
-        with:
-          sha: ${{ steps.commit.outputs.sha }}
-      # Prepares env vars for use in a PR comment or issue in `solidity-verifier`
-      - name: Set env vars
-        if: steps.solidity-test.outcome != 'success'
-        run: |
-          WORKFLOW_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+            PR_NUMBER=$(echo ${{ github.event.merge_group.head_ref }} | sed -e 's/.*pr-\(.*\)-.*/\1/')
+          fi
+          GITHUB_URL=https://github.com/${{ github.repository }}
+          WORKFLOW_URL=$GITHUB_URL/actions/runs/${{ github.run_id }}
+          PR_URL=$GITHUB_URL/pull/$PR_NUMBER
           echo "WORKFLOW_URL=$WORKFLOW_URL" | tee -a $GITHUB_ENV
           echo "WORKFLOW_FILE=$WORKFLOW_URL/workflow" | tee -a $GITHUB_ENV
-          echo "COMMIT=${{ steps.commit.outputs.sha }}" | tee -a $GITHUB_ENV
-          echo "PR_URL=${{ steps.pr.outputs.prUrl }}" | tee -a $GITHUB_ENV
-      - name: Comment on failing run
-        if: steps.solidity-test.outcome != 'success'
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          issue-number: ${{ github.event.issue.number }}
-          body: |
-            `solidity-verifier` compatibility test failed :x:
+          echo "COMMIT=$SHA" | tee -a $GITHUB_ENV
+          echo "PR_URL=$PR_URL" | tee -a $GITHUB_ENV
+      #- name: Comment on failing run
+      #  if: steps.solidity-test.outcome != 'success' && github.event_name == 'pull_request'
+      #  uses: peter-evans/create-or-update-comment@v4
+      #  with:
+      #    issue-number: ${{ github.event.pull_request.number }}
+      #    body: |
+      #      `solidity-verifier` compatibility test failed :x:
 
-            ${{ env.WORKFLOW_URL }}
-      #- uses: actions/checkout@v4
+      #      ${{ env.WORKFLOW_URL }}
+      # Open issue in downstream repo
+      - uses: actions/checkout@v4
         #if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')         
-        #with:
-          #repository: lurk-lab/solidity-verifier
+        with:
+          repository: lurk-lab/ci-workflows
+      # Have to check out the upstream repo again to get the issue template
+      # Ideally we'd run JasonEtco/create-an-issue in a subdirectory but this isn't possible
+      - uses: actions/checkout@v4
+        #if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')         
+        with:
+          repository: lurk-lab/ci-lab
+          path: ${{ github.workspace }}/template
+          sparse-checkout: |
+            .github/templates/SOLIDITY_COMPAT_ISSUE.md
+          sparse-checkout-cone-mode: false
+      - run: |
+          find $PWD/template/.github/* -type f
+        #if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')
       - uses: JasonEtco/create-an-issue@v2
-        if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')         
+        #if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
@@ -82,4 +89,7 @@ jobs:
           PR_URL: ${{ env.PR_URL }}
         with:
           update_existing: true
-          filename: .github/templates/SOLIDITY_COMPAT_ISSUE.md
+          filename: ${{ github.workspace }}/template/.github/templates/SOLIDITY_COMPAT_ISSUE.md
+      # Prevent merge of required check (test)
+      - if: steps.solidity-test.outcome != 'success' && (github.event_name != 'pull_request' || github.event.action == 'enqueued')
+        run: exit 1
